module.exports = {
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    UNAUTHORIZED_OPERATION: "UNAUTHORIZED_OPERATION",
    INVALID_PASSWORD: "INVALID_PASSWORD",
    EMAIL_TAKEN: "EMAIL_TAKEN",
    INVALID_EMAIL: "INVALID_EMAIL",
    ARE_U_SERIOUS: "ARE_U_SERIOUS",
    UNSECURED_PASSWORD: "UNSECURED_PASSWORD",
};
